#!/usr/bin/perl

use strict;

use Getopt::Std;

# Jonathan Ledlie
# originally written Nov 5, 2000

my $usage = "Usage: random\n".
  "         -t [pareto]".
  "         -a parameter".
  "         -b parameter";

my %para = ();

getopts('t:', \%para);

if (!defined($para{'t'})) {
  print "$usage\n";
  exit (-1);
}

for (my $i = 0; $i < 10; $i++) {
  &
}
