#!/usr/bin/perl

use strict;

if ($#ARGV != 1 && $#ARGV != 0) {
	die "Usage: trim filename [max line length].\n";
}
my $file = $ARGV[0];
my $maxLineLength = 70;

if ($#ARGV == 1) {
  $maxLineLength = $ARGV[1];
}

open IN, $file or die ("Cannot open $file");

my @text = ();
while (my $line = <IN>) {
  my (@words) = split (/\s/, $line);
  push (@text, @words);
}
close IN;

my $i = 0;
my $linelength = 0;
while ($i <= $#text) {
  if ($linelength + length ($text[$i]) > $maxLineLength) {
    print "\n";
    $linelength = 0;
  }
  $linelength += length ($text[$i]);
  print "$text[$i] ";
  $i++;
}

